var data_rules = {
'1.1':'Ultimate is a non-contact, self-refereed sport. All players are responsible for administering and adhering to the rules. Ultimate relies upon a Spirit of the Game that places the responsibility for fair play on every player.',
'1.2':'It is trusted that no player will intentionally break the rules; thus there are no harsh penalties for inadvertent breaches, but rather a method for resuming play in a manner which simulates what would most likely have occurred had there been no breach.',
'1.3':'Players should be mindful of the fact that they are acting as referees in any arbitration between teams. Players must:',
'1.3.1':'know the rules;',
'1.3.2':'be fair-minded and objective;',
'1.3.3':'be truthful;',
'1.3.4':'explain their viewpoint clearly and briefly; ',
'1.3.5':'allow opponents a reasonable chance to speak;',
'1.3.6':'resolve disputes as quickly as possible, using respectful language;',
'1.3.7':'make calls in a consistent manner throughout the game; and ',
'1.3.8':'only make a call where a breach is significant enough to make a difference to the outcome of the action.',
'1.4':'Highly competitive play is encouraged, but should never sacrifice the mutual respect between players, adherence to the agreed-upon rules of the game, or the basic joy of play.',
'1.5':'The following actions are examples of good spirit:',
'1.5.1':'informing a team-mate if they have made a wrong or unnecessary call or caused a foul or violation;',
'1.5.2':'retracting a call when you no longer believe the call was necessary;',
'1.5.3':'complimenting an opponent for good play or spirit;',
'1.5.4':'introducing yourself to your opponent; and',
'1.5.5':'reacting calmly towards disagreement or provocation.',
'1.6':'The following actions are clear violations of the spirit of the game and must be avoided by all participants:',
'1.6.1':'dangerous play and aggressive behaviour;',
'1.6.2':'intentional fouling or other intentional rule violations;',
'1.6.3':'taunting or intimidating opposing players;',
'1.6.4':'disrespectful celebration after scoring;',
'1.6.5':'making calls in retaliation to an opponent’s call; and',
'1.6.6':'calling for a pass from an opposition player.',
'1.7':'Teams are guardians of the Spirit of the Game, and must:',
'1.7.1':'take responsibility for teaching their players the rules and good spirit;',
'1.7.2':'discipline players who display poor spirit; and',
'1.7.3':'provide constructive feedback to other teams about how to improve their adherence to the Spirit of the Game.',
'1.8':'In the case where a novice player commits a breach out of ignorance of the rules, experienced players are obliged to explain the breach.',
'1.9':'An experienced player, who offers advice on rules and guides on-field arbitration, may supervise games involving beginners or younger players.',
'1.10':'Rules should be interpreted by the players directly involved in the play, or by players who had the best perspective on the play. Non-players, apart from the captain, should refrain from getting involved. However players may seek the perspective of non-players to clarify the rules, and to assist players to make the appropriate call.',
'1.11':'Players and captains are solely responsible for making all calls. ',
'1.12':'If, after discussion, players cannot agree, or it is unclear:',
'1.12.1':'what occurred in a play, or',
'1.12.2':'what would most likely have occurred in a play, the disc must be returned to the last non-disputed thrower.',
'2.1':'The playing field is a rectangle area with dimensions and zones as shown on Figure 1 (see above) and should be essentially flat, free of obstructions and afford reasonable player safety.',
'2.2':'The perimeter lines surround the playing field and consist of two (2) sidelines along the length and two (2) endlines along the width.',
'2.3':'The perimeter lines are not part of the playing field.',
'2.4':'The goal lines are the lines that separate the central zone from the end zones and are part of the central zone.',
'2.5':'The brick mark is the intersection of two (2) crossed one (1) metre lines in the central zone set eighteen (18) metres from each goal line, midway between the sidelines.',
'2.6':'Eight brightly-coloured, flexible objects (such as plastic cones) mark the corners of the central zone and the end zones.',
'2.7':'The immediate surroundings of the playing field shall be kept clear of movable objects. If play is obstructed by non-players or objects within three (3) metres of the perimeter line, any obstructed player or thrower in possession may call "Violation".',
'3.1':'Any flying disc acceptable to both captains may be used.',
'3.2':'WFDF may maintain a list of approved discs recommended for use.',
'3.3':'Each player must wear a uniform that distinguishes their team. ',
'3.4':'No player may wear items of clothing or equipment that reasonably could harm the wearer or other players, or impede an opponent\'s ability to play. ',
'4.1':'A game consists of a number of points. Each point ends with the scoring of a goal.',
'4.2':'A game is finished and won by the first team to score fifteen (15) goals. ',
'4.3':'A game is separated into two (2) periods of play, called halves.  Half time occurs when a team first scores eight (8) goals.',
'4.4':'The first point of each half starts when the half starts.',
'4.5':'After a goal is scored, and the game has not been won or half time has not been reached:',
'4.5.1':'the next point starts immediately;',
'4.5.2':'the teams switch the end zone that they are defending; and',
'4.5.3':'the team that scored becomes defence and pulls next.',
'4.6':'A variation of the basic structure may be used to accommodate special competitions, number of players, age of players or available space.',
'5.1':'Each team will put a maximum of seven (7) players and a minimum of five (5) players on the field during each point. ',
'5.2':'A team may make (unlimited) substitutions after a goal is scored and before the team signals readiness for the pull.',
'5.3':'Each team will nominate a captain to represent the team.',
'6.1':'Representatives of the two teams fairly determine which team first chooses either:',
'6.1.1':'whether to receive or throw the initial pull; or',
'6.1.2':'which end zone they will initially defend.',
'6.2':'The other team is given the remaining choice.',
'6.3':'At the start of the second half, these initial selections are switched.',
'7.1':'At the start of the game, after half-time or after a score, play commences with a throw-off, called a pull. ',
'7.1.1':'Teams must prepare for the pull without unreasonable delay. ',
'7.2':'The pull may be made only after both teams have signalled their readiness by having the puller and a player on offence raise a hand above their head.',
'7.3':'After signalling readiness all offensive players must stand with one foot on their defending goal line without changing location relative to one another until the pull is released.',
'7.4':'After signalling readiness all defensive players must keep their feet entirely behind the vertical plane of the goal line until the pull is released.',
'7.5':'If a team breaches 7.3 or 7.4 the opposing team may call a violation ("offside"). This must be called before the receiving team touches the disc and the pull must be repeated as quickly as possible.',
'7.6':'As soon as the disc is released, all players may move in any direction.',
'7.7':'No player on the defensive team may touch the disc after a pull until a member of the offensive team contacts the disc or the disc contacts the ground. ',
'7.8':'If an offensive player, in-bounds or out-of-bounds, touches the disc before it hits the ground, and the offensive team fails to catch it, that is a turnover (a "dropped pull").',
'7.9':'If an offensive player catches the pull they must establish a pivot at the point on the playing field nearest to where it was caught, even if that point is in their defending end zone.',
'7.10':'If the disc initially contacts the playing field and never becomes out-of-bounds, the thrower must establish the pivot where the disc stops, even if that point is in their defending end zone. ',
'7.11':'If the disc initially contacts the playing field and then becomes out-of-bounds without contacting an offensive player, the thrower must establish the pivot where the disc first crossed the perimeter line, or the nearest point in the central zone if that point would be in the defending end zone. ',
'7.11.1':'If the disc does contact an offensive player before it becomes out-of-bounds the thrower must establish the pivot where the disc first crossed the perimeter line, even if that point is in their defending end zone.',
'7.12':'If the disc contacts the out-of-bounds area without first touching the playing field or an offensive player, the thrower may establish the pivot either at the brick mark closest to their defending end zone, or at the spot on the central zone closest to where the disc went out-of-bounds (Section 11.7).  The binding brick option must be signalled before the disc is picked up, by any offensive player fully extending one arm overhead and calling "brick". ',
'8.1':'The disc is dead, and no turnover is possible:',
'8.1.1':'After the start of a point, until the pull is released;',
'8.1.2':'After the pull or after a turnover when the disc must be carried to the location of the correct pivot point, until a pivot is established; or ',
'8.1.3':'After a call which stops the play or any other stoppage, until the disc is checked in. ',
'8.2':'A disc that is not dead is live.',
'8.3':'The thrower may not transfer possession of a dead disc to another player.',
'8.4':'Any player may attempt to stop a disc from rolling or sliding after it has hit the ground.',
'8.4.1':'If, in attempting to stop such a disc, a player significantly alters the disc’s position, the opposition may request that the pivot be established at the location where the disc was contacted.',
'8.5':'After a turnover, and after the pull, the team that has gained possession of the disc must continue play without delay.',
'8.5.1':'An offensive player must move at walking pace or faster to directly retrieve the disc and establish a pivot.',
'8.5.2':'In addition to 8.5.1, after a turnover the offence must put the disc into play within the following time limits, if the disc did not become out-of-bounds, and the discs location is: ',
'8.5.2.1':'in the central zone – within ten (10) seconds of the disc coming to rest.',
'8.5.2.2':'in an end zone - within twenty (20) seconds of the disc coming to rest.',
'8.5.3':'If the offence breaches 8.5 the defence may give a verbal warning ("Delay of Game") or may call a "Violation".',
'8.5.4':'If an offensive player is within three (3) metres of the pivot point and, after the verbal warning, the offence continues to breach 8.5 the marker may commence the stall count. ',
'9.1':'The marker administers a stall count on the thrower by announcing "Stalling" and then counting from one (1) to ten (10).  The interval between the start of each number in the stall count must be at least one (1) second.',
'9.2':'The stall count must be clearly audible to the thrower.',
'9.3':'The marker may only start and continue a stall count when: ',
'9.3.1':'The disc is live (unless specified otherwise);',
'9.3.2':'They are within three (3) metres of the thrower, or the correct pivot point if the thrower has moved from that spot; and',
'9.3.3':'All defenders are legally positioned (Section 18.1).',
'9.4':'If the marker moves more than three (3) metres from the thrower, or a different player becomes the marker, the stall count must be restarted at "Stalling one (1)".',
'9.5':'After play stops the stall count is resumed as follows:',
'9.5.1':'After an uncontested breach by the defence the stall count restarts at "Stalling one (1)".',
'9.5.2':'After an uncontested breach by the offence the stall count restarts at maximum nine (9).',
'9.5.3':'After a contested stall-out the stall count restarts at "Stalling eight (8)".',
'9.5.4':'After all other calls, including "pick", the stall count restarts at maximum six (6). ',
'9.6':'To restart a stall count "at maximum n", where "n" is determined by 9.5.2, or 9.5.4, means the following:',
'9.6.1':'If "x" is the last number fully uttered prior to the call, then the stall count resumes at "Stalling (x plus one)" or "Stalling n", whichever of those two numbers is lower. ',
'10.1':'Whenever play stops during a point for a time-out, foul, violation, contested turnover, specified turnover, contested goal, technical stoppage, injury stoppage, or discussion, play must restart as quickly as possible with a check. The check may only be delayed for the discussion of a call. ',
'10.2':'Player positioning after a call (except in the case of a time-out, and unless specified otherwise):',
'10.2.1':'If play stops before a pass is thrown, all players must return to the location they held when the call was made.',
'10.2.2':'If play stops after a pass is thrown, then:',
'10.2.2.1':'if the disc is returned to the thrower, all players must return to the location they held when the thrower released the disc, or the time of the call, whichever is earlier.',
'10.2.2.2':'if the result of the play stands all players must return to the location they held when either the pass was caught, or the disc hit the ground.',
'10.2.2.3':'if a player other than the thrower gains possession as a result of an uncontested breach, all players must return to the location they held when the breach occurred.',
'10.2.3':'All players must remain stationary in that location until the disc is checked in.',
'10.3':'Any player may briefly extend a stoppage of play to fix faulty equipment ("equipment"), but active play may not be stopped for this purpose. ',
'10.4':'The person checking the disc in must first verify with the nearest opposition player that their team is ready.',
'10.4.1':'If there is an unnecessary delay in checking the disc in, the opposition may give a verbal warning ("Delay of Game") and, if the delay continues, they may check the disc in by calling "Disc In", without verification from the opposition. ',
'10.5':'To restart play: ',
'10.5.1':'when the thrower has the disc:',
'10.5.1.1':'if there is a defender within reach, the defender must touch the disc.',
'10.5.1.2':'if there is not a defender within reach, the thrower must touch the disc to the ground and should call "Disc In".',
'10.5.2':'when the disc is on the ground, the defender nearest to the disc must call "Disc In".',
'10.6':'If the thrower attempts a pass before the check, or a violation of 10.2 is called, the pass does not count regardless of whether it is complete or incomplete, and possession reverts back to the thrower. ',
'11.1':'The entire playing field is in-bounds. The perimeter lines are not part of the playing field and are out-of-bounds.  All non-players are part of the out-of-bounds area.',
'11.2':'The out-of-bounds area consists of the area which is not in-bounds and everything in contact with it, except for defensive players, who are always considered "in-bounds" for purposes of making a play on the disc.',
'11.3':'An offensive player who is not out-of-bounds is in-bounds.',
'11.3.1':'An airborne player retains their in-bounds/out-of-bounds status until that player contacts the playing field or the out-of-bounds area. ',
'11.3.2':'A thrower in possession of the disc, who contacts the playing field and then touches an out-of-bounds area, is still considered in-bounds.',
'11.3.2.1':'If the thrower leaves the playing field, they must establish the pivot at the spot on the playing field where they crossed the perimeter line (unless 14.2 is in effect).',
'11.3.3':'Contact between players does not confer the state of being in- or out-of-bounds from one to another.',
'11.4':'A disc is in-bounds once it is live, or when play starts or restarts.',
'11.5':'A disc becomes out-of-bounds when it first contacts the out-of-bounds area or contacts an out-of-bounds offensive player.  A disc in the possession of an offensive player has the same in/out-of-bounds status as that player.  If the disc is simultaneously in the possession of more than one offensive player, one of them being out-of-bounds, the disc is out-of-bounds.',
'11.6':'The disc may fly outside a perimeter line and return to the playing field, and players may go out-of-bounds to make a play on the disc. ',
'11.7':'The place where a disc went out-of-bounds is the spot where, prior to contacting an out-of-bounds area or player, the disc was most recently: ',
'11.7.1':'partly or wholly over the playing field; or',
'11.7.2':'contacted by an in-bounds player.',
'11.8':'If the disc is out-of-bounds and more than three (3) metres from the pivot point, non-players may retrieve the disc.  The thrower must carry the disc the last three (3) metres to the playing field.',
'12.1':'A player "catches" the disc by demonstrating sustained control of a non-spinning disc.',
'12.2':'If the player loses control of the disc due to subsequent contact with the ground or a team-mate or a legitimately positioned opposition player, the catch is deemed to have not occurred.',
'12.3':'The following are out-of-bounds turnovers, and no catch is deemed to have occurred: ',
'12.3.1':'an offensive receiver is out-of-bounds when they contact the disc; or',
'12.3.2':'after catching the disc, an offensive receiver’s first contact is out-of-bounds while still in possession of the disc.',
'12.4':'After a catch, that player becomes the thrower.',
'12.5':'If offensive and defensive players catch the disc simultaneously, the offence retains possession.',
'12.6':'A player in an established position is entitled to remain in that position and should not be contacted by an opposing player.',
'12.7':'Every player is entitled to occupy any position on the field not occupied by any opposing player, provided that they do not initiate contact in taking such a position. ',
'12.7.1':'However when the disc is in the air a player may not move in a manner solely to prevent an opponent from taking an unoccupied path to the disc.  ',
'12.8':'All players must attempt to avoid contact with other players, and there is no situation where a player may justify initiating contact.  "Making a play for the disc" is not a valid excuse for initiating contact with other players.  ',
'12.9':'Some incidental contact , not affecting the outcome of the play or safety of players, may occur as two or more players move towards a single point simultaneously.  Incidental contact should be minimized but is not considered a foul. ',
'12.10':'Players may not use their arms or legs to obstruct the movement of opposing players.',
'12.11':'No player may physically assist the movement of another player, nor use an item of equipment to assist in contacting the disc.',
'13.1':'A turnover that transfers possession of the disc from one team to the other occurs when:',
'13.1.1':'the disc contacts the ground while it is not in the possession of an offensive player (a "down"); ',
'13.1.2':'a pass is caught by a defensive player (an "interception");',
'13.1.3':'the disc becomes out-of bounds (an "out-of-bounds"); or',
'13.1.4':'during the pull, the receiving team touches the disc before it contacts the ground, and fails to catch the disc (a "dropped pull").',
'13.2':'A turnover that transfers possession of the disc from one team to the other, and results in a stoppage of play, occurs when:',
'13.2.1':'there is an uncontested offensive receiving foul;',
'13.2.2':'the thrower has not released the disc before the marker first starts to say the word "ten" in the stall count (a "stall-out");',
'13.2.3':'the disc is intentionally transferred from one offensive player to another without ever being completely untouched by both players (a "hand-over");',
'13.2.4':'the thrower intentionally deflects a pass to themselves off another player (a "deflection");',
'13.2.5':'in attempting a pass, the thrower catches the disc after release prior to the disc being contacted by another player (a "double touch"); ',
'13.2.6':'an offensive player intentionally assists a teammate’s movement to catch a pass; or',
'13.2.7':'an offensive player uses an item of equipment to assist in catching a pass.',
'13.3':'If a player determines a turnover has occurred they must make the appropriate call immediately.  If the opposition disagrees they may call "contest". If, after discussion, players cannot agree or it is unclear what occurred in the play, the disc must be returned to the last non-disputed thrower.',
'13.4':'If a fast count occurs in such a manner that the offence does not have a reasonable opportunity to call fast count before a stall-out, the play is treated as a contested stall-out (9.5.3).',
'13.4.1':'If the thrower contests a stall-out but also attempts a pass, and the pass is incomplete, then the turnover stands and play restarts with a check.',
'13.5':'Any offensive player may take possession of the disc after a turnover, except:',
'13.5.1':'after an "interception" turnover, in which case the player who made the interception must maintain possession; and ',
'13.5.2':'after an offensive receiving foul, in which case the fouled player must take possession.',
'13.6':'If the player in possession after a turnover intentionally drops the disc, or places the disc on the ground, they must re-establish possession and restart play with a check.  ',
'13.7':'After a turnover, the turnover location is where:',
'13.7.1':'the disc has come to a stop or is picked up by an offensive player; or',
'13.7.2':'the intercepting player stops; or',
'13.7.3':'the thrower was located, in the case of 13.2.2, 13.2.3, 13.2.4, 13.2.5; or',
'13.7.4':'the offensive player was located, in the case of 13.2.6 and 13.2.7; or',
'13.7.5':'the uncontested offensive receiving foul occurred.',
'13.8':'If the turnover location is out-of-bounds, or the disc touched an out-of-bounds area after the turnover occurred, the thrower must establish a pivot at the spot on the central zone nearest to where the disc went out-of-bounds (Section 11.7). ',
'13.8.1':'If 13.8 does not apply, the pivot must be established according to 13.9, 13.10, or 13.11..',
'13.9':'If the turnover location is in the central zone, the thrower must establish the pivot at that point.',
'13.10':'If the turnover location is in the offence’s attacking end zone, the thrower must establish the pivot at the nearest point on the goal line.',
'13.11':'If the turnover location is in the offence’s defending end zone, the thrower may choose where to establish the pivot:',
'13.11.1':'at the turnover location, by staying at the turnover location or faking a pass; or',
'13.11.2':'at the nearest point on the goal line to the turnover location, by moving from the turnover location.',
'13.11.2.1':'The intended thrower, before picking up the disc, may signal the goal line option by fully extending one arm above their head. ',
'13.11.3':'Immediate movement, failure to move, or signaling the goal line option determines where to establish the pivot and cannot be reversed. ',
'13.12':'If, after a turnover, play has continued unknowingly, play stops and the disc is returned to the turnover location, players resume their positions at the time the turnover occurred and play restarts with a check.',
'14.1':'A goal is scored if an in-bounds player catches a legal pass and all of their first simultaneous points of contact after catching the disc are entirely within their attacking end zone (note 12.1, 12.2).  ',
'14.1.1':'If a player believes a goal has been scored they may call "goal" and play stops. After a contested or retracted goal call play must restart with a check and the call is deemed to have been made when the pass was caught. ',
'14.2':'If a player in possession of the disc ends up with their selected pivot behind the attacking goal line without scoring a goal according to 14.1, the player establishes the pivot at the nearest point of the goal line.',
'14.3':'The time at which a goal is scored is when the disc is caught and the player in possession is in contact with the end zone.',
'15.1':'A breach of the rules due to non-incidental contact between two or more opposing players is a foul. ',
'15.2':'A breach of the rules regarding a Marking or Travel breach is an infraction.  Infractions do not stop play.',
'15.3':'Every other breach of the rules is a violation.',
'15.4':'Only the player fouled may claim a foul, by calling "Foul".',
'15.5':'Only the thrower may claim a marking infraction, by calling the specific name of the infraction. Any opposing player may claim a travel infraction. ',
'15.6':'Any opposing player may claim a violation, by calling the specific name of the violation or "Violation", unless specified otherwise by the particular rule.',
'15.7':'When a foul or violation call is made that stops play, players must stop play by visibly or audibly communicating the stoppage as soon as they are aware of the call and all players should echo calls on the field. If play has stopped for a discussion without any call having been made, a call is deemed to have been made when the discussion started.',
'15.8':'Calls must be made immediately after the breach is recognised.',
'15.9':'After a player initiates a stoppage incorrectly, including after mishearing a call, not knowing the rules, or not making the call immediately:',
'15.9.1':'if the opposition gains or retains possession, any subsequent play stands.',
'15.9.2':'if the opposition does not gain or retain possession, the disc must be returned to the last non-disputed thrower.',
'15.10':'If the player against whom the foul, infraction or violation has been called disagrees that it occurred, they may call "Contest".',
'15.11':'If a player making the "Foul", "Violation" or "Contest" call subsequently determines that their call was incorrect, they can retract the call, by calling "Retracted".  Play restarts with a check.',
'16.1':'Whenever a foul or violation call is made, play stops immediately and no turn over is possible (unless in situations specified in 15.9, 16.2, and 16.3). ',
'16.2':'If the foul or violation:',
'16.2.1':'is called against the thrower and the thrower subsequently attempts a pass, or',
'16.2.2':'is called when the thrower is in the act of throwing, or',
'16.2.3':'is called or occurs when the disc is in the air, then play continues until possession has been established.',
'16.2.4':'Once possession has been established:',
'16.2.4.1':'If the team that called the foul or violation gains or retains possession as a result of the pass, play continues without a stoppage. Players recognizing this may call "Play on" to indicate that this rule has been invoked.',
'16.2.4.2':'If the team that called the foul or violation does not gain or retain possession as a result of the pass, play must be stopped.',
'16.2.4.2.1':'If the team that called the foul or violation believes that possession has been affected by the foul or violation, the disc will be returned to the thrower for a check (unless the specific rule says otherwise).',
'16.3':'Regardless of when the foul or violation call is made, if play had not completely stopped and the players involved from both teams agree that the foul, violation or call did not affect the outcome , the play stands. This rule is not superseded by any other rule.',
'16.3.1':'If the play resulted in a goal, the goal stands.',
'16.3.2':'If the play did not result in a goal the affected players may make up any positional disadvantage caused by the foul, violation or call and restart play with a check.',
'17.1':'Dangerous Play:',
'17.1.1':'Reckless disregard for the safety of fellow players is considered dangerous play and is to be treated as a foul, regardless of whether or when contact occurs.  This rule is not superseded by any other rule. If uncontested this must be treated as the most relevant foul from Section 17.',
'17.2':'Defensive Receiving (Defender) Fouls:',
'17.2.1':'A Defensive Receiving Foul occurs when a defender initiates contact with a receiver before, while, or directly after, either player makes a play on the disc. ',
'17.2.2':'After an uncontested defensive receiving foul the receiver gains possession at the point of the breach. If 14.2 applies, the disc is dead until a pivot is established at the nearest point of the goal line. If the foul is contested, the disc is returned to the thrower.',
'17.3':'Force-out Fouls:',
'17.3.1':'A Force-out Foul occurs when an airborne receiver catches the disc, and is fouled by a defensive player before landing, and the contact caused the receiver;',
'17.3.1.1':'to land out-of-bounds instead of in-bounds; or',
'17.3.1.2':'to land in the central zone instead of their attacking end zone.',
'17.3.2':'If the receiver would have landed in their attacking end zone, it is a goal;',
'17.3.3':'If the force-out foul is contested, the disc is returned to the thrower if the receiver landed out-of-bounds, otherwise the disc stays with the receiver.',
'17.4':'Defensive Throwing (Marking) Fouls: ',
'17.4.1':'A Defensive Throwing Foul occurs when:',
'17.4.1.1':'A defensive player is illegally positioned (Section 18.1), and there is contact with the thrower; or',
'17.4.1.2':'A defensive player initiates contact with the thrower, or there is contact resulting from the thrower and the defender both vying for the same unoccupied position, prior to the release.',
'17.4.1.3':'If a Defensive Throwing Foul occurs prior to the thrower releasing the disc and not during the throwing motion, the thrower may choose to call a contact infraction, by calling "Contact". After a contact infraction that is not contested, play does not stop and the marker must resume the stall count at one (1).',
'17.5':'Strip Fouls:',
'17.5.1':'A Strip Foul occurs when a defensive foul causes the receiver or thrower to drop the disc after they have gained possession.',
'17.5.2':'If the reception would have otherwise been a goal, and the foul is uncontested, a goal is awarded.',
'17.6':'Offensive Receiving Fouls: ',
'17.6.1':'An Offensive Receiving Foul occurs when a receiver initiates contact with a defensive player before, while, or directly after, either player makes a play on the disc. ',
'17.6.2':'If the foul is uncontested, the result is a turnover, and the defensive player gains possession at the point of the breach.',
'17.6.3':'If the pass is complete and the foul is contested, the disc returns to the thrower.',
'17.7':'Offensive Throwing (Thrower) Fouls:',
'17.7.1':'An Offensive Throwing Foul occurs when the thrower initiates contact with a defensive player who is in a legal position. ',
'17.7.2':'Incidental contact occurring during the thrower\'s follow through is not sufficient grounds for a foul, but should be avoided.',
'17.8':'Blocking Fouls:',
'17.8.1':'A Blocking Foul occurs when a player takes a position that a moving opponent will be unable to avoid and contact results, and is to be treated as either a receiving foul or an indirect foul, whichever is applicable. ',
'17.9':'Indirect Fouls:',
'17.9.1':'An Indirect Foul occurs when there is contact between a receiver and a defensive player that does not directly affect an attempt to make a play on the disc. ',
'17.9.2':'If uncontested the fouled player may make up any positional disadvantage caused by the foul.',
'17.10':'Offsetting Fouls:',
'17.10.1':'If fouls are called by offensive and defensive players on the same play, the disc returns to the thrower.',
'17.10.2':'Non incidental contact that occurs as two or more opposing players move towards a single point simultaneously should be treated as offsetting fouls. ',
'18.1':'Marking Infractions:',
'18.1.1':'Marking infractions include the following:',
'18.1.1.1':'"Fast Count" – the marker:',
'18.1.1.1.1':'starts the stall count before the disc is live,',
'18.1.1.1.2':'does not start or restart the stall count with the word "Stalling",',
'18.1.1.1.3':'counts in less than one second intervals,',
'18.1.1.1.4':'does not correctly reduce or reset the stall count when required, or',
'18.1.1.1.5':'does not start the stall count from the correct number.',
'18.1.1.2':'"Straddle" – a line between a defensive player’s feet contains the thrower’s pivot point.',
'18.1.1.3':'"Disc Space" – any part of a defensive player is less than one disc diameter away from the torso of the thrower.  However, if this situation is caused solely by movement of the thrower, it is not an infraction.',
'18.1.1.4':'"Wrapping" – a line between a defensive player’s hands or arms intersects the thrower’s torso, or any part of the defensive player’s body is above the thrower’s pivot point. However, if this situation is caused solely by movement of the thrower, it is not an infraction.',
'18.1.1.5':'"Double Team" –a defensive player other than the marker is within three (3) metres of the thrower\'s pivot point without also guarding another offensive player. However, merely running across this area is not a double team.',
'18.1.1.6':'"Vision" - a defensive player uses any part of their body to intentionally obstruct the thrower’s vision.',
'18.1.2':'A marking infraction may be contested by the defence, in which case play stops.',
'18.1.3':'After all marking infractions listed in 18.1.1 that are not contested, the marker must resume the stall count with the number last fully uttered before the call, minus one (1).',
'18.1.4':'The marker may not resume counting until any illegal positioning has been corrected.  To do otherwise is a subsequent marking infraction.',
'18.1.5':'Instead of calling a marking infraction, the thrower may call a marking violation and stop play if;',
'18.1.5.1':'the stall count is not corrected,',
'18.1.5.2':'there is no stall count,',
'18.1.5.3':'there is an egregious marking infraction, or',
'18.1.5.4':'there is a pattern of repeated marking infractions.',
'18.1.6':'If the thrower calls a marking infraction, or a marking violation, and also attempts a pass before, during or after the call, the call has no consequences and if the pass is incomplete, then the turnover stands. However if the disc is returned to thrower for a separate breach, the stall count must be adjusted accordingly.',
'18.2':'"Travel" Infractions: ',
'18.2.1':'The thrower may attempt a pass at any time as long as they are entirely in-bounds or have established an in-bounds pivot.',
'18.2.1.1':'However an in-bounds player who catches a pass while airborne may attempt a pass prior to contacting the ground.',
'18.2.2':'After catching the disc, and landing in-bounds, the thrower must reduce speed as quickly as possible, without changing direction, until they have established a pivot point.',
'18.2.2.1':'The thrower may release the disc while reducing speed as long as they maintain contact with the playing field throughout the throwing motion.',
'18.2.3':'The thrower may change direction ("pivot") only by establishing a "pivot point", where one part of their body remains in constant contact with a certain spot on the playing field, called the "pivot point".',
'18.2.4':'A thrower who is lying down or kneeling does not need to establish a pivot.',
'18.2.4.1':'If they stand up it is not a travel, provided the pivot is established at the same location.',
'18.2.5':'A travel infraction occurs if: ',
'18.2.5.1':'the thrower establishes the pivot at an incorrect point on the playing field;',
'18.2.5.2':'the thrower changes direction before establishing a pivot or releasing the disc;',
'18.2.5.3':'after a catch the thrower fails to reduce their speed as quickly as possible;',
'18.2.5.4':'the thrower fails to keep the established pivot until releasing the disc;',
'18.2.5.5':'the thrower fails to maintain contact with the playing field throughout the throwing motion; or',
'18.2.5.6':'a player purposefully bobbles, fumbles or delays the disc to themselves in order to move in any direction.',
'18.2.6':'After an uncontested travel infraction is called ("travel"), play does not stop. ',
'18.2.6.1':'The thrower establishes a pivot at the correct spot, as indicated by the player who called the travel.  This must occur without delay from either player involved.',
'18.2.6.2':'Any stall count is paused, and the thrower may not throw the disc, until the pivot is established at the correct spot.',
'18.2.6.3':'The marker must say "Stalling" before restarting the stall count.',
'18.2.7':'If, after a travel infraction but before correcting the pivot, the thrower throws a completed pass, the defensive team may call a travel violation.  Play stops and the disc is returned to the thrower. The thrower must return to the location occupied at the time of the infraction. Play must restart with a check.',
'18.2.8':'If, after a travel infraction, the thrower throws an incomplete pass, play continues.',
'18.2.9':'After a contested travel infraction where the thrower has not released the disc, play stops.',
'18.3':'"Pick" Violations:',
'18.3.1':'If a defensive player is guarding one offensive player and they are prevented from moving towards/with that player by another player, that defensive player may call "Pick". However it is not a pick if both the player being guarded and the obstructing player are making a play on the disc.',
'18.3.1.1':'Prior to making the "Pick" call, the defender may delay the call up to two (2) seconds to determine if the obstruction will affect the play.',
'18.3.2':'If play has stopped, the obstructed player may move to the agreed position they would have otherwise occupied if the obstruction had not occurred, unless specified otherwise.',
'18.3.3':'All players should take reasonable efforts to avoid the occurrence of picks.',
'18.3.3.1':'During any stoppage opposing players may agree to slightly adjust their locations to avoid potential picks.',
'19.1':'Injury Stoppage',
'19.1.1':'An injury stoppage, "Injury", may be called by the injured player, or by any player on the injured player’s team.',
'19.1.2':'If any player has an open or bleeding wound, an injury stoppage must be called and that player must take an immediate injury substitution and must not rejoin the game until the wound is treated and sealed.',
'19.1.3':'If the injury was not caused by an opponent, the player must choose either to be substituted, or to charge their own team with a Time-Out. ',
'19.1.4':'If the injury was caused by an opponent the player may choose to stay or to be substituted.',
'19.1.5':'If the injured player had caught the disc, and the player has dropped the disc due to the injury, that player retains possession of the disc.',
'19.1.6':'The injury stoppage is considered to have been called at the time of the injury, unless the injured player chooses to continue play before the stoppage is called.',
'19.1.7':'If the disc was in the air when the injury stoppage was called, play continues until either the pass is caught, or the disc hits the ground. If the injury is not the result of a foul, the completion or turnover stands, and play restarts there after the stoppage.',
'19.2':'Technical Stoppage',
'19.2.1':'Any player who recognises a condition that endangers players may call "technical" to stop play. Play must stop immediately.',
'19.2.2':'The thrower may call a technical stoppage during play to replace a severely damaged disc. ',
'19.2.3':'After a technical stoppage call:',
'19.2.3.1':'If the call or issue did not affect play, the completion or turnover stands, and play restarts there;',
'19.2.3.2':'If the call or issue did affect the play, the disc goes back to the thrower.',
'19.3':'If a player is substituted after an injury, or technical stoppage due to illegal equipment, the opposing team may also choose to substitute one player.',
'19.3.1':'Substitute players take on the full state (location, possession, stall count etc) of the player they are substituting.',
'20.1':'The player calling a time-out must form a "T" with their hands, or with one hand and the disc, and should call "time-out" audibly to opposition players.',
'20.2':'Each team may take two (2) time-outs per half.',
'20.3':'After the start of a point and before both teams have signalled readiness, a player from either team may call a time-out. The time-out extends the time between the start of the point and subsequent pull by seventy-five (75) seconds.',
'20.4':'After the pull only a thrower with possession of the disc that has survived ground contact, may call a time-out. The time-out starts when the "T" is formed, and lasts seventy-five (75) seconds. After such a time-out: ',
'20.4.1':'Substitutions are not allowed, except for injury.',
'20.4.2':'Play is restarted at the pivot point.',
'20.4.3':'The thrower remains the same.',
'20.4.4':'All other offensive players may then set up at any point on the playing field.',
'20.4.5':'Once the offensive players have selected positions, defensive players may set up at any point on the playing field.',
'20.4.6':'The stall count remains the same, unless the marker has been switched.',
'20.5':'If the thrower attempts to call a time-out when their team has no remaining time-outs, play is stopped. The marker must add two (2) seconds to the stall count they would have restarted play on before restarting play with a check. If this results in a stall count of ten (10) or above, this is a "stall-out" turnover.'
,'Definitions':'https://rules.wfdf.org/definitions'
};
